### ISSUE TITLE
Eyewitness 

### ISSUE THREAD

**Issue by jaikishantulswani** [cakinney/domained#16]
Hello,

swtich to skip eyewitness ?
Its too good if you give a   ##switch to skip eyewitness.

**Comment by cakinney** [comment]
Thanks and great idea!

**Comment by jaikishantulswani** [comment]
Hey @cakinney 
Any updates for the new release ?

**Comment by cakinney** [comment]
@jaikishantulswani Thanks for your patience! I have updated domained with a no EyeWitness option. `--noeyewitness`. Thanks for the great suggestion.

**Comment by jaikishantulswani** [comment]
Hey @cakinney , 
This is too FAST !!!
Thank you for the update :)
