### ISSUE TITLE
sublister issue

### ISSUE THREAD

**Issue by jaikishantulswani** [cakinney/domained#17]
Traceback (most recent call last):
  File "domained.py", line 489, in <module>
    sublist3r()
  File "domained.py", line 99, in sublist3r
    os.system(Subcmd)
TypeError: <lambda>() takes exactly 1 argument (2 given)

**Comment by jaikishantulswani** [comment]
Traceback (most recent call last):
  File "domained.py", line 489, in <module>
    sublist3r()
  File "domained.py", line 99, in sublist3r
    os.system(Subcmd)
TypeError: <lambda>() takes exactly 1 argument (2 given)

**Comment by cakinney** [comment]
Thanks, can you please try to run it from Sublist3r? navigate to `domained/bin/Sublist3r` and run `python sublist3r.py -d example.com` and let me know if error persists. [Sublist3r Readme](https://github.com/aboul3la/Sublist3r).

**Comment by jaikishantulswani** [comment]
Hello @cakinney ,
Sublist3r is working perfectly fine from domained/bin/Sublist3, then what's the issue while running from domained.py ?

**Comment by jaikishantulswani** [comment]
Hello @cakinney ,

Any  updates !

**Comment by cakinney** [comment]
Sorry for the delay, I am trying to reproduce, but I do not get the same error, what operating system are you using and what domained command?

**Comment by jaikishantulswani** [comment]
@cakinney ,
Thank you for your reply, I am using Kali Linux and the command I run is 
python domained.py -d redactedtarget.com --bruteall --noeyewitness
and still getting the same issue
Traceback (most recent call last):
  File "domained.py", line 489, in <module>
    sublist3r()
  File "domained.py", line 99, in sublist3r
    os.system(Subcmd)
TypeError: <lambda>() takes exactly 1 argument (2 given)

**Comment by jaikishantulswani** [comment]
@cakinney ,
My bad , the issue has been resolved by removing and installing it again :)

Thank you !!!

**Comment by cakinney** [comment]
No problem! Glad it's fixed, thanks!
