### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by jaikishantulswani** [cakinney/domained#18]
Hello @cakinney ,
domained is working good with --noeyewitness switch, if you include SubOver / Subjack (Domain Takeover) with a switch to check domain flyovers too after completing the domain enumeration then it will become a pretty good one to go tool.

**Comment by cakinney** [comment]
Thanks for the suggestion, SubOver looks like a great tool. I will look into adding it to domained.

**Comment by jaikishantulswani** [comment]
Waiting for that release :)

**Comment by jaikishantulswani** [comment]
Hello @cakinney ,
Any updates for the new domained :+1:

**Comment by jaikishantulswani** [comment]
@cakinney Thank  You ! :+1:

**Comment by cakinney** [comment]
SubOver was discontinued but SubFinder was added.
