### ISSUE TITLE
massdns error

### ISSUE THREAD

**Issue by RnmX** [cakinney/domained#19]
Hello guys,

I was experimenting with this tools recently I and found it's current implementation does not work well with massdns. I noticed the sublister which is used by domained (/bin/sublister/sublister.py) behaves differently from sublister.py which is presented in /bin/massdns/sublister.py. If I run "python domained.py -b domain.com -b --bruteall" I never actually get to see massdns's "status screen" and it looks like it got stuck.

I was able to make it work by changing these lines:
massdnsCMD = 'python {} -s {} {} | {} -r resolvers.txt -t A -a -o -w {}-massdns.txt -'.format(
os.path.join(script_path, 'bin/subbrute/subbrute.py'), word_file, domain,

to look like this:

massdnsCMD = 'python {} {} {} | {} -r resolvers.txt -t A -a -o -w {}-massdns.txt -'.format(
os.path.join(script_path, 'bin/massdns/subbrute.py'), word_file, domain,

Then it works perfectly fine.

Thanks!

**Comment by cakinney** [comment]
@RnmX Thanks for reporting the issue (and the fix!) with the masscan command! If you would like to do a pull request I will get it tested and merged ASAP or if not I can update and push out.

**Comment by cakinney** [comment]
@RnmX Thank you for your patience. I am still testing this to ensure that removing the `-s` flag does not just appear to be working faster because it has SubBrute bypass the large word list and if so, would it be beneficial to have another function (replacing or additional) to interact with massdns without SubBrute?

**Comment by RnmX** [comment]
Hello there!

Sorry for not replying but I was off for holidays. How is your testing going?
