### ISSUE TITLE
Idea: Try using SubFinder

### ISSUE THREAD

**Issue by Ice3man543** [cakinney/domained#20]
Hey there, 
Domained is a great wrapper for combining lots of tool. 

Since development on the sublist3r tool was really slow, we (a bunch of guys)  decided to build subfinder. It's a successor to the sublist3r project improving it a thousand times. It has 30+ sources and many bells and whistles. 

Try it out.

**Comment by cakinney** [comment]
@Ice3man543 Thanks! Issue #18 also recommended adding SubOver. Both tools are great and if you are okay with me adding them to domained, I'll add them in the next release.

**Comment by cakinney** [comment]
@Ice3man543 thanks!  I just merged the SubOver pull request! #24 from @apoorvrajsaxena.

**Comment by Ice3man543** [comment]
Nice and subover is dropped. It's SubFinder, :p

**Comment by cakinney** [comment]
Corrected :)
