### ISSUE TITLE
Sublister Errors Out while scaning particular domains

### ISSUE THREAD

**Issue by rahulr311295** [cakinney/domained#23]
The script  errors out after running sublister and gathering the output

Traceback (most recent call last):
  File "domained.py", line 489, in <module>
    sublist3r()
  File "domained.py", line 99, in sublist3r
    os.system(Subcmd)
TypeError: <lambda>() takes exactly 1 argument (2 given)

**Comment by ituseye** [comment]
> The script errors out after running sublister and gathering the output
> 
> Traceback (most recent call last):
> File "domained.py", line 489, in 
> sublist3r()
> File "domained.py", line 99, in sublist3r
> os.system(Subcmd)
> TypeError: () takes exactly 1 argument (2 given)

This happened to me too, Baidu Engine threads was taking too long to respond after scanning a lot, For the time being, I've removed Baidu Enumerator from Sublist3r. 
Line no. 912 of sublist3r.py remove baiduEnum

**Comment by cakinney** [comment]
Thank you - please report Sublist3r issues to the [Sublist3r Issue Tracker](https://github.com/aboul3la/Sublist3r/issues).
