### ISSUE TITLE
Error in the EyeWitness

### ISSUE THREAD

**Issue by robdollard** [cakinney/domained#26]
At startup, an error occurs.
![1024c2fde4cde896e4ecd2a9d1790c95](https://user-images.githubusercontent.com/40629638/48696455-ce008e00-ec03-11e8-95db-0aee38966267.png)

**Comment by cakinney** [comment]
Thank you - please report issues with EyeWitness to the [EyeWitness Issue Tracker](https://github.com/FortyNorthSecurity/EyeWitness/issues).
